uktrade/market-access-python-frontend

reports/constants.py
reports/forms/new_report_barrier_summary.py
reports/helpers.py
reports/urls.py
reports/views.py
templates/reports/new_report_barrier_summary.html

add form and view for [Step 5 - Barrier summary] in the add a barrier journey

MAR-118 - add a barrier - step 5 - summary

---

config/settings/base.py

Per the results of the pen test:
```
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```
Also use secure cookies and the HttpOnly flag

MAR-235: Set security headers

---

core/static/js/components/AttachmentForm.js
core/static/js/ma.js
templates/barriers/assessments/economic.html
templates/barriers/barrier_detail.html

Fix per:
https://docs.djangoproject.com/en/3.0/ref/csrf/#s-acquiring-the-token-if-csrf-use-sessions-or-csrf-cookie-httponly-is-true

MAR-255: Fix CSRF token for ajax uploads

---

barriers/forms/search.py
barriers/forms/wto.py
barriers/views/wto.py
templates/barriers/edit/wto/profile.html
templates/barriers/find_a_barrier.html
tests/barriers/test_find_a_barrier.py

* Ensure WTO search filters OR together instead of AND
* Show WTO form regardless of if WTO should be notified (just with fewer fields)

MAR-343: WTO 'or' filters

---

barriers/views/search.py
templates/users/manage.html
tests/barriers/test_search.py
users/views.py
utils/pagination.py

* Add pagination to manage users list
* Tidy up `PaginationMixin`

MAR-472: Add pagination to manage users list

---

barriers/forms/public_barriers.py
templates/partials/forms/text_input.html
templates/partials/forms/textarea.html

* Add style guide links to public barrier title and summary forms
* Increase public summary character count to 1000

MAR-530: Add style guide links to public barrier title and summary forms

---

barriers/constants.py
barriers/forms/notes.py
barriers/forms/public_barriers.py
barriers/forms/search.py
barriers/models/barriers.py
barriers/models/history/barriers.py
barriers/models/history/public_barriers.py
core/frontend/src/js/react/commodities/CommodityForm.js
templates/barriers/activity/partials/barrier/public_eligibility_summary.html
templates/barriers/activity/partials/public_barrier/public_view_status.html
templates/barriers/edit/commodities.html
templates/barriers/history/partials/barrier/public_eligibility_summary.html
templates/barriers/history/partials/public_barrier/public_view_status.html
templates/barriers/public_barriers/detail.html
templates/barriers/public_barriers/eligibility.html
templates/barriers/public_barriers/title.html

* Update the terminology used in the public barrier tab

MAR-545: Update the terminology used in the public barrier tab

---

barriers/forms/search.py
barriers/models/barriers.py
templates/barriers/public_barriers/detail.html
tests/barriers/test_models.py

* Allow searching by public id
* Display public id on public view page

MAR-531: Allow searching by public id

---

core/frontend/src/js/react/search/LocationFilter.js
templates/barriers/forms/statuses/dormant.html
templates/barriers/forms/statuses/open_in_progress.html
templates/barriers/forms/statuses/open_pending.html
templates/barriers/forms/statuses/resolved_in_full.html
templates/barriers/forms/statuses/resolved_in_part.html
templates/barriers/forms/statuses/unknown.html
templates/barriers/search.html
templates/base.html
templates/partials/forms/radio_input.html
templates/partials/forms/widgets/month_year_widget.html
templates/reports/new_report_barrier_trade_direction.html
tests/reports/test_location_views.py

* Remove duplicate ids
* Ensure inputs have correct labels/legends

MAR-448: Accessibility

---

templates/barriers/dashboard.html
templates/barriers/partials/saved_search_badges.html

MAR-391 - update labels for badges on dashboard

---

barriers/models/history/barriers.py
core/fixtures/metadata.json
tests/barriers/test_history.py
utils/metadata.py

Update frontend for model changes in the API

MAR-516: Tidy up modelling

---

barriers/views/assessments/economic.py

* Prevent form from getting saved twice

Fix form getting saved twice

---

package-lock.json
package.json

This is to fix security issues here https://github.com/uktrade/market-access-python-frontend/security/dependabot

Security: dependabot dep upgrade

---

tests/barriers/test_download_barriers.py
utils/api/resources.py

Following on from MAR-940 remove the dead code. Also rename test variable names
to make it clear what is being tested here.

MAR-1032: remove dead code

---

templates/barriers/search.html

Still waiting to hear what to do about "resolved in part" barriers.

TSS-143: Show resolution date in search results.

---

barriers/forms/search.py
barriers/views/search.py
config/settings/base.py
core/fixtures/metadata.json
core/frontend/src/css/pages/_search.scss
core/frontend/src/js/pages/barrier/search.js
templates/barriers/search.html
tests/barriers/test_download_barriers.py
tests/barriers/test_search.py
utils/metadata.py
webpack.config.js

Reverts uktrade/market-access-python-frontend#322

Revert "TSS-347 sort by dropdown"

---

barriers/forms/search.py
barriers/views/search.py
config/settings/base.py
core/fixtures/metadata.json
core/frontend/src/css/pages/_search.scss
core/frontend/src/js/pages/barrier/search.js
templates/barriers/search.html
tests/barriers/test_download_barriers.py
tests/barriers/test_search.py
utils/metadata.py
webpack.config.js

TSS-347 sort by dropdown

---

templates/barriers/search.html

Unbelievably lightweight pull request 😀

Fix filter for PB100 barriers.

---

core/fixtures/metadata.json
docker/local/Dockerfile
package-lock.json
package.json

Switches to using the same major/minor versions of Ubuntu and Python in the local Docker environment as are used on the GovUK PaaS servers.
To ensure a clean rebuild, stop your existing container and use:
```bash
docker compose build --no-cache
```

Tech Debt: Update Linux

---

reports/model_forms/new_report_barrier_about.py

Report a barrier 'about the barrier' page updates

Another go at error messages

---

barriers/forms/commodities.py
barriers/forms/statuses.py
barriers/views/commodities.py
reports/model_forms/new_report_barrier_location.py
reports/model_forms/new_report_barrier_sectors.py
reports/model_forms/new_report_barrier_status.py
reports/model_forms/new_report_barrier_summary.py
tests/barriers/test_commodities.py
utils/forms.py

Should be all of the rest of the report a barrier errors. Goodness the code is, ahem, interesting.

Tss 423 error messages continued

---

barriers/constants.py
barriers/forms/search.py
core/fixtures/metadata.json
core/frontend/src/css/app-components/_checkbox-filter.scss
templates/barriers/history/partials/barrier/top_priority_status.html
templates/barriers/partials/barrier_summary.html
templates/barriers/search.html
templates/partials/forms/checkbox_filter.html

Update display name/labels on search filters and rename "Asia Pacific Cross-Government Pilot" tag

Update Search labels

---

poetry.lock
pyproject.toml
requirements.txt

Update Django, werkzeug and cryptography

security_patches_feb_23

---

reports/report_barrier_forms.py
reports/report_barrier_view.py
templates/reports/barrier_sectors_affected_wizard_step.html
templates/reports/barrier_trade_direction_wizard_step.html

Prototype for multi value select component

MVE sectors form multi value component

---

core/frontend/src/js/react/commodities/CommodityForm.js
reports/report_barrier_forms.py
reports/report_barrier_view.py
reports/views.py
templates/reports/barrier_export_type_wizard_step.html
templates/reports/new_report.html

Prototype of React component integration

MVE - goods and services form

---

core/frontend/src/js/react/commodities/CommodityForm.js
reports/report_barrier_forms.py
reports/report_barrier_view.py
templates/reports/barrier_export_type_wizard_step.html

Fixed loading of country/trading bloc options in commodity form. Allow the submission of commodity codes relating to Countries and Trading Blocs on the single form

MVE add commodities form

---

reports/report_barrier_view.py
templates/barriers/barrier_detail.html
templates/reports/barrier_status_wizard_step.html
tests/barriers/test_models.py
tests/barriers/test_search.py

Added export description to barrier summary page
"i don't know" checkbox checked when the user returns to step 2 report a barrier.
Remvoed redundant critical logging statements, leftover from dev

Fix - TSS-888 - TSS-887 - TSS-886 - Report/Edit a barrier fixes

---

core/fixtures/metadata.json

Added Department for Culture, Media and Sport to metadata.json

Feature - TSS-905 - Add new government organisation

---

barriers/forms/search.py
barriers/views/search.py
config/settings/base.py

Decreasing pagination size and removing redundant code

Fix - TSS-931 - Duplicates in search results

---

barriers/views/edit.py
core/fixtures/metadata.json
tests/barriers/test_edit_barrier_fields.py

Added scoping tag to metadata and removed redundant get_context_data call

Feature - TSS-966 - Create scoping tag

---

barriers/views/edit.py
core/fixtures/metadata.json
tests/barriers/test_edit_barrier_fields.py

This reverts commit cbb0cc3bef5397bf199e311aa4125155438b1c5c.

Revert "Feature - TSS-966 - Create scoping tag (#505)"

---

barriers/forms/feedback.py
poetry.lock
pyproject.toml
requirements.txt
templates/feedback.html

* Add two additional question to CSAT feedback form
* Add two new CSAT - Feedback questions
* Tidy up
* Add conditional for other-detail field
* Conditional reveal for Other Detail checkbox
* Tidy up
* Allow CSAT submission
* Add validation for both Feedback journeys
* Formatting
* Formating
* touching html
* touching html
* touching html
* re-indenting
---------

sprint-42-a-new-hope-release-1

---

barriers/forms/edit.py
barriers/forms/search.py
barriers/views/edit.py
core/frontend/src/css/app-objects/_tags.scss
core/frontend/src/js/pages/barrier/top_barrier_priority.js
templates/barriers/partials/barrier_summary.html
templates/barriers/search.html
tests/barriers/fixtures/barriers.json
tests/barriers/test_edit_barrier_fields.py
ui_tests/test_barrier_priority.py

changing regional priority reference to overseas priority

Feature - TSS-1004 - Change regional priority to overseas priority

---

core/fixtures/metadata.json

Feature - TSS-1036 - EU priority tag

---

barriers/views/sectors.py
tests/barriers/test_edit_sectors.py

you cannot select main sector from the 'other sectors' dropdown.
Added tests

Fix - TSS-987 - Main sector duplication

---

barriers/forms/edit.py
barriers/forms/various.py
barriers/urls.py
barriers/views/progress_updates.py
templates/barriers/barrier_detail.html
templates/barriers/progress_updates/add_barrier_update.html
templates/barriers/progress_updates/list_programme_fund.html
templates/barriers/progress_updates/list_top_100.html

* Remove references to Top 100 for progress updates in the UI. API mapping/endpoints left unchanged
* Formatting
* Add help text to Delivery Confidence field
* iSort formating
* Update templates/barriers/progress_updates/add_barrier_update.html
* Formatting
---------

Release - Man Uka of Lord - a

---

config/settings/base.py
templates/barriers/search.html

added google-analytics.com CSP header

Fix - Adding new google tag manager CSP header

---

barriers/models/history/barriers.py
utils/forms/fields.py

Fixing persistent sentry errors:
https://sentry.ci.uktrade.digital/organizations/dit/issues/102415/?environment=production&environment=prod&project=121&project=169&query=is%3Aunresolved
https://sentry.ci.uktrade.digital/organizations/dit/issues/99560/?environment=production&environment=prod&project=121&project=169&query=is%3Aunresolved

Fix - TSS-1360 - Persistent sentry errors

---

barriers/views/search.py
tests/barriers/test_download_barriers.py

fixing bug where multiple-choice search filters were removed after downloading

Fix - TSS-1359 - Search filter removed when downloading CSV

---

.github/dependabot.yml

only allowing security updates

Fix - Only allowing dependabot security updates

---

barriers/models/history/public_barriers.py

PublicBarrierLocation is called country and not actually location

Fix - TSS-1398 - Fixing public barrier location history

---

config/settings/base.py
config/settings/dev.py
config/settings/local.py
config/settings/uat.py
users/constants.py
users/forms.py
users/views.py

- Move permission constants out of settings
- Set Role Admin in additional user permissions by default

TSS-1464: Permission grouping for admin

---

users/constants.py

* TSS-1580: Related Barrier feture flag
* format
---------

TSS-1580: Related Barrier feature flag (#636)

---

barriers/forms/edit.py
templates/barriers/barrier_detail.html
templates/barriers/progress_updates/add_programme_fund_update.html

tss-1691: barrier help texts

---

templates/accessibility.html

Update Accessibility statement

Feature/tss 1880/update accessibility statement

---

templates/reports/barrier_status_wizard_step.html

TSS-1434: Accessibility - Barrier Status Radio Buttons

---

barriers/views/assessments/economic.py
templates/barriers/assessments/economic/automate.html
tests/assessments/test_economic_assessments.py

Removal of automated financial assessment feature due to the retirement of Comtrade datasets
Delete redundant tests
Fix tests

Remove automated financial assessments

---

core/frontend/src/css/pages/barrier/_detail.scss

* fix keyboard navigation and focus
* Fix formating
* feat focus and hover highlights the star
---------

Sprint 63 - T-Regz and TRUST - 2

---

core/frontend/src/js/react/dashboard/charts.js
core/frontend/src/js/react/index.js
package-lock.json
package.json
templates/barriers/home.html
templates/barriers/partials/dashboard-charts.html
webpack.config.js

@ferozerub a heads up based on the library: https://github.com/apexcharts/react-apexcharts/issues/219

TSS-1967 dmas-dashboard-v-2-dashboard-charts

---

barriers/urls.py
barriers/views/mixins.py
barriers/views/related_barriers.py
templates/barriers/partials/barrier_tabs.html
templates/barriers/related_barriers.html
templates/base.html
tests/barriers/test_public_barriers_view.py
utils/api/resources.py

First version of related barriers

Related barrier POC

---

.circleci/config.yml
barriers/views/core.py
tests/users/account/test_mentions.py

Redirect the user to the new homepage if no previous preference set

TSS 2611 - Default to new dashboard
